# Stock and flows





## Building stock

```{r stock vars}
total <- c(all = "Stock|Buildings",
           res = "Stock|Residential",
           com = "Stock|Commercial")
```

```{r stock overview}
if (all(total %in% data$variable)) {
  showAreaAndBarPlots(data, vars = total[c("res", "com")], tot = total[["all"]],
                      orderVars = "user", scales = "fixed")
}
```

```{r stock loop, results='asis'}
for (sec in names(total)) {
  tot <- total[[sec]]
  
  if (!tot %in% data$variable) next
  
  heading(sec, 3)
  
  showAreaBarLinePlots(data = data, tot = tot, items = type,
                       heading = "by Building type", nHeading = 4)
  
  showAreaBarLinePlots(data = data, tot = tot, items = location,
                       heading = "by Location", nHeading = 4)
  
  showAreaBarLinePlots(data = data, tot = tot, items = vintage,
                       heading = "by Construction cohort", nHeading = 4,
                       showLines = FALSE)
  
  showAreaBarLinePlots(data = data, tot = tot, items = heating,
                       heading = "by Space heating", nHeading = 4)
}
```





## Net yearly building stock change

```{r stock change vars}
total <- c(all = "Net stock change|Buildings",
           res = "Net stock change|Residential",
           com = "Net stock change|Commercial")
```

```{r stock change loop, results='asis'}
for (sec in names(total)) {
  tot <- total[[sec]]
  
  if (!tot %in% data$variable) next
  
  heading(sec, 3)
  
  showAreaBarLinePlots(data = data, tot = tot, items = heating,
                       heading = "by Space heating", nHeading = 4)
}
```





## Construction flow

```{r construction vars}
total <- c(all = "Construction|Buildings",
           res = "Construction|Residential",
           com = "Construction|Commercial")
```

```{r construction overview}
if (all(total %in% data$variable)) {
  showAreaAndBarPlots(data, vars = total[c("res", "com")], tot = total[["all"]],
                      orderVars = "user", scales = "fixed")
}
```

```{r construction loop, results='asis'}
for (sec in names(total)) {
  tot <- total[[sec]]
  
  if (!tot %in% data$variable) next
  
  heading(sec, 3)
  
  showAreaBarLinePlots(data = data, tot = tot, items = type,
                       heading = "by Building type", nHeading = 4)
  
  showAreaBarLinePlots(data = data, tot = tot, items = location,
                       heading = "by Location", nHeading = 4)
  
  showAreaBarLinePlots(data = data, tot = tot, items = heating,
                       heading = "by Space heating", nHeading = 4)
}
```





## Renovation flow of the shell

```{r shell renovation vars}
total <- c(all = "Renovation|Buildings|Shell",
           res = "Renovation|Residential|Shell",
           com = "Renovation|Commercial|Shell")
```

```{r shell renovation overview}
if (all(total %in% data$variable)) {
  showAreaAndBarPlots(data, vars = total[c("res", "com")], tot = total[["all"]],
                      orderVars = "user", scales = "fixed")
}
```

```{r shell renovation loop, results='asis'}
for (sec in names(total)) {
  tot <- total[[sec]]
  
  if (!tot %in% data$variable) next
  
  heading(sec, 3)
  
  showAreaBarLinePlots(data = data, tot = tot, items = type,
                       heading = "by Building type", nHeading = 4)
  
  showAreaBarLinePlots(data = data, tot = tot, items = location,
                       heading = "by Location", nHeading = 4)
  
  showAreaBarLinePlots(data = data, tot = tot, items = paste0("Initial|", shell),
                       heading = "by Building shell (initial state)", nHeading = 4,
                       showTot = FALSE, showLines = FALSE)
  
  showAreaBarLinePlots(data = data, tot = tot, items = paste0("Final|", shell),
                       heading = "by Building shell (final state)", nHeading = 4,
                       showTot = FALSE, showLines = FALSE)
  
  showAreaBarLinePlots(data = data, tot = tot, items = identRepl,
                       heading = "by identical replacement or not", nHeading = 4)
}
```





## Renovation flow of the heating system

```{r heating renovation vars}
total <- c(all = "Renovation|Buildings|Heating",
           res = "Renovation|Residential|Heating",
           com = "Renovation|Commercial|Heating")
identReplHeating <- identRepl %>%
  paste0(c("", "|Final")) %>%
  outer(heating, paste, sep = "|") %>%
  as.character()
```

```{r heating renovation overview}
showAreaAndBarPlots(data, vars = total[c("res", "com")], tot = total[["all"]], 
                    orderVars = "user", scales = "fixed")
```

```{r heating renovation loop, results='asis'}
for (sec in names(total)) {
  tot <- total[[sec]]
  
  if (!tot %in% data$variable) next
  
  heading(sec, 3)
  
  showAreaBarLinePlots(data = data, tot = tot, items = type,
                       heading = "by Building type", nHeading = 4)
  
  showAreaBarLinePlots(data = data, tot = tot, items = location,
                       heading = "by Location", nHeading = 4)
  
  showAreaBarLinePlots(data = data, tot = tot, items = paste0("Initial|", heating),
                       heading = "by Space heating (initial state)", nHeading = 4,
                       showTot = FALSE)
  
  showAreaBarLinePlots(data = data, tot = tot, items = paste0("Final|", heating),
                       heading = "by Space heating (final state)", nHeading = 4,
                       showLines = FALSE, showTot = FALSE)
  
  showAreaBarLinePlots(data = data, tot = tot, items = paste0("Final|", heating0),
                       heading = "by Space heating (final state, with zero renovation)", nHeading = 4,
                       showTot = FALSE)
  
  showAreaBarLinePlots(data = data, tot = tot, items = identRepl,
                       heading = "by Identical replacement or not", nHeading = 4)
  
  showAreaBarLinePlots(data = data, tot = tot, items = identReplHeating,
                       heading = "by Identical replacement or not and by Heating system", nHeading = 4,
                       showTot = FALSE, showLines = FALSE)
  for (hs in heating) {
    showAreaAndBarPlots(data = data,
                        tot = paste0(tot, "|Final|", hs),
                        vars = paste(tot, grep(hs, identReplHeating, value = TRUE), sep = "|"))
  }
}
```
